### ISSUE TITLE
[Crash]使用邮箱登陆的crash

### ISSUE THREAD

**Issue by xfoxfu** [wang4yu6peng13/MaterialQQLite#2]
log如下

```
HARDWARE=mx2
M9=M9
RADIO=unknown
AUTORECORDER=true
HOST=mz-builder-6
CUSTOMIZE_CHINAUNICOM=false
MX_DEVICE=2
PERMANENTKEY=false
M045=M045
ID=KTU84P
M046=M046
TYPE=user
TIME=1422218402000
FINGERPRINT=Meizu/meizu_mx2/mx2:4.4.4/KTU84P/m04x.Flyme_OS_4.1.5.20150126040827:user/release-keys
CUSTOMIZE_PCCW=false
UNKNOWN=unknown
BOARD=meizu_mx2
PRODUCT=meizu_mx2
versionName=0.3
DEVICE=mx2
MODEL=M040
BOOTLOADER=unknown
CTA=noncta
CPU_ABI2=armeabi
HAS_SMARTBAR=true
MZ_USE_NAVBAR=false
IS_MX3=false
IS_WCDMA_PLATFORM=true
IS_MX2=true
IS_MX=false
MX3_DEVICE=8
versionCode=3
IS_PCCW=false
sInternational=-1
M9_DEVICE=1
TAGS=release-keys
M065=M353
VOICEMAIL=true
BUILD_MASK=4.4.4-1422216507_dev
MANUFACTURER=Meizu
MeizuSecurity=true
CUSTOMIZE_ISP_VALUE=unknown
NFC_INFO=false
IS_M9=false
M040=M040
IS_AGENCY=false
SUPPORT_MZ_NFC_P2P_FEATURE=8
IS_PRODUCT=true
CUSTOMIZE_CHINAMOBILE=false
DISPLAY=Flyme OS 4.1.5A (体验版)
MX2_DEVICE=4
USER=flyme
HAS_PERMANENTKEY=false
IS_TD_PLATFORM=false
CPU_ABI=armeabi-v7a
MEIZU_SECURITY=true
IS_FLYMEROM=false
IS_DEBUGGABLE=false
M032=M032
M030=M030
SERIAL=040BBGD8WFRT
M031=M031
BRAND=Meizu
IS_SHOPDEMO=false
java.lang.NumberFormatException: Invalid long: "xfox@cotr.me"
    at java.lang.Long.invalidLong(Long.java:124)
    at java.lang.Long.parse(Long.java:361)
    at java.lang.Long.parseLong(Long.java:352)
    at java.lang.Long.parseLong(Long.java:318)
    at com.wyp.materialqqlite.qqclient.QQClient.setUser(QQClient.java:190)
    at com.wyp.materialqqlite.ui.LoginActivity$1.handleMessage(LoginActivity.java:64)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5054)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
```

使用邮箱登陆有问题

如果用QQ号登陆就没有问题……

**Comment by fython** [comment]
233333
